import "./globals.css";

export const metadata = {
  title: "Smart Watch",
  description: "Generated by create next app",
  icon: {
    icon: ["./../../favicon.ico"],
    apple: ["./../../apple-touch-icon.png"],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
